USE onlineStore;
CREATE TABLE IF NOT EXISTS products(
    product_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    category_id INTEGER REFERENCES category(category_id),
    product_name VARCHAR(255) NOT NULL,
    product_quantity INTEGER NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL

);



-- DROP TABLE products;

insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (1, 3, 'Wine - Muscadet Sur Lie', 81405, 7087.12);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (2, 7, 'Table Cloth 90x90 White', 40899, 7017.25);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (3, 2, 'Veal - Inside Round / Top, Lean', 51735, 3308.64);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (4, 8, 'Hipnotiq Liquor', 53933, 9490.66);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (5, 3, 'Beer - Steamwhistle', 77667, 8826.41);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (6, 1, 'Table Cloth - 53x69 Colour', 11476, 1561.89);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (7, 9, 'Versatainer Nc - 888', 41240, 8938.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (8, 7, 'Cabbage - Red', 3540, 3454.21);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (9, 3, 'Dry Ice', 5203, 3490.58);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (10, 2, 'Hot Choc Vending', 78226, 366.3);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (11, 5, 'Saskatoon Berries - Frozen', 25377, 375.96);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (12, 6, 'Coke - Classic, 355 Ml', 74161, 5261.01);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (13, 10, 'Celery', 97340, 5543.58);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (14, 2, 'Bread - Sour Batard', 64540, 404.03);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (15, 9, 'Olives - Kalamata', 29719, 7363.33);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (16, 10, 'Rice Paper', 54076, 4879.13);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (17, 5, 'Eggwhite Frozen', 62870, 1879.39);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (18, 2, 'Oil - Margarine', 65744, 7245.31);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (19, 8, 'Beef - Tenderloin Tails', 58058, 3694.68);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (20, 9, 'Chocolate - Sugar Free Semi Choc', 31071, 4454.73);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (21, 2, 'Puree - Raspberry', 71943, 2652.02);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (22, 7, 'C - Plus, Orange', 92176, 9032.87);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (23, 8, 'Vaccum Bag 10x13', 97963, 2514.91);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (24, 4, 'Towel - Roll White', 59408, 5456.97);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (25, 9, 'Skewers - Bamboo', 99777, 8715.14);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (26, 4, 'Soup - Base Broth Chix', 41681, 3183.19);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (27, 3, 'Wine - Red, Concha Y Toro', 43450, 2350.01);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (28, 6, 'Vegetable - Base', 5550, 802.19);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (29, 3, 'Muffin Mix - Blueberry', 72665, 9220.0);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (30, 2, 'Wine - Trimbach Pinot Blanc', 32934, 42.38);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (31, 3, 'Petit Baguette', 90181, 6737.76);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (32, 7, 'Cheese - Havarti, Roasted Garlic', 72474, 6771.17);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (33, 4, 'Pork - European Side Bacon', 43626, 1559.43);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (34, 5, 'Pumpkin', 23232, 4992.33);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (35, 7, 'Soup - Campbells Beef Noodle', 61917, 7038.77);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (36, 10, 'Beef - Tenderloin - Aa', 78697, 3154.87);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (37, 4, 'Bread - Corn Muffaletta', 27728, 5592.73);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (38, 8, 'Zucchini - Mini, Green', 36993, 4116.56);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (39, 2, 'Mop Head - Cotton, 24 Oz', 14523, 5066.54);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (40, 9, 'Flour - Masa De Harina Mexican', 13010, 1034.99);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (41, 3, 'Scotch - Queen Anne', 14156, 6941.36);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (42, 4, 'Quail Eggs - Canned', 33090, 5864.81);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (43, 3, 'Shrimp, Dried, Small / Lb', 78300, 4871.44);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (44, 6, 'V8 - Tropical Blend', 71112, 5483.97);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (45, 8, 'Sansho Powder', 22153, 7943.92);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (46, 10, 'Kaffir Lime Leaves', 850, 7736.98);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (47, 9, 'Rice - Basmati', 43372, 2621.94);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (48, 3, 'Syrup - Golden, Lyles', 20839, 2637.49);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (49, 10, 'Wine - Alsace Riesling Reserve', 29313, 2740.9);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (50, 3, 'Tomatoes - Diced, Canned', 47534, 3929.77);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (51, 4, 'Sauce - White, Mix', 93320, 805.07);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (52, 3, 'Bread - White Mini Epi', 81679, 6102.64);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (53, 10, 'Mushroom - Crimini', 4680, 288.1);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (54, 1, 'Sprouts - Peppercress', 70943, 1094.11);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (55, 5, 'Chestnuts - Whole,canned', 49498, 6512.6);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (56, 9, 'Cumin - Whole', 79492, 9828.89);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (57, 8, 'Flour - Bread', 48850, 482.18);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (58, 8, 'Sprouts - Baby Pea Tendrils', 53113, 2846.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (59, 1, 'Coffee Cup 16oz Foam', 8670, 9662.51);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (60, 5, 'Aspic - Light', 84738, 5991.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (61, 8, 'Garlic - Elephant', 62968, 6112.42);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (62, 9, 'Muffin Hinge Container 6', 94349, 5332.43);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (63, 3, 'Juice - Ocean Spray Cranberry', 83601, 8077.44);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (64, 8, 'Pasta - Cannelloni, Sheets, Fresh', 2144, 6702.38);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (65, 7, 'Cheese - Cheddar, Old White', 78889, 1423.77);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (66, 10, 'Coffee Caramel Biscotti', 72491, 3526.5);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (67, 6, 'Beer - Moosehead', 26807, 8486.8);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (68, 3, 'Cheese - Brick With Onion', 4674, 5236.05);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (69, 5, 'Sugar - Cubes', 98931, 8158.86);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (70, 4, 'Beer - Labatt Blue', 25507, 6674.51);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (71, 6, 'Flounder - Fresh', 93892, 9955.03);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (72, 5, 'Halibut - Steaks', 80991, 2423.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (73, 3, 'Phyllo Dough', 2898, 4464.92);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (74, 2, 'Pork - Hock And Feet Attached', 85558, 5860.03);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (75, 3, 'Mushroom - Morels, Dry', 98795, 6393.75);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (76, 8, 'Artichokes - Jerusalem', 23939, 7123.94);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (77, 3, 'Vinegar - Rice', 48616, 9141.58);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (78, 2, 'Bread - English Muffin', 60308, 2504.0);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (79, 3, 'Rice - Basmati', 48616, 2825.18);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (80, 9, 'Bamboo Shoots - Sliced', 48830, 5007.03);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (81, 1, 'Raspberries - Frozen', 92108, 2878.45);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (82, 2, 'Table Cloth 62x120 Colour', 32006, 6319.45);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (83, 7, 'Wine - Crozes Hermitage E.', 42988, 1090.47);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (84, 5, 'Onions Granulated', 16248, 4407.43);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (85, 6, 'Island Oasis - Strawberry', 11326, 9976.08);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (86, 7, 'Sauce - Black Current, Dry Mix', 65964, 4785.94);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (87, 2, 'Turkey - Ground. Lean', 1822, 1924.6);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (88, 1, 'Juice - Mango', 54331, 4257.81);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (89, 5, 'Bamboo Shoots - Sliced', 44699, 9551.28);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (90, 4, 'Tea - Herbal Sweet Dreams', 72932, 539.93);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (91, 5, 'Peas Snow', 26615, 8019.14);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (92, 3, 'Hickory Smoke, Liquid', 35907, 814.52);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (93, 6, 'Yogurt - Peach, 175 Gr', 41115, 3875.07);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (94, 7, 'Trout - Smoked', 95013, 7151.59);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (95, 6, 'Wine - Chablis J Moreau Et Fils', 99490, 7466.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (96, 1, 'Boogies', 73367, 4201.37);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (97, 7, 'Bread - Multigrain', 16133, 1096.66);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (98, 4, 'Flower - Carnations', 91039, 665.97);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (99, 4, 'Soup - Campbells Mushroom', 27316, 1680.75);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (100, 6, 'Appetizer - Southwestern', 93379, 9298.52);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (101, 8, 'Gelatine Leaves - Envelopes', 49106, 4820.88);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (102, 6, 'Clam - Cherrystone', 21799, 3730.8);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (103, 10, 'Water - Green Tea Refresher', 72914, 6675.93);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (104, 7, 'Lid - 10,12,16 Oz', 23629, 89.42);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (105, 8, 'Bandage - Finger Cots', 48275, 1196.45);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (106, 2, 'Cheese - Comtomme', 48509, 9555.65);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (107, 9, 'Milk - Chocolate 500ml', 54900, 3100.17);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (108, 4, 'Truffle - Peelings', 25903, 5268.29);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (109, 8, 'Wine - Alsace Gewurztraminer', 63929, 4144.99);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (110, 2, 'Couscous', 43617, 6245.94);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (111, 8, 'Tea - Grapefruit Green Tea', 32265, 4146.31);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (112, 8, 'Veal - Ground', 3522, 5417.63);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (113, 8, 'Spice - Paprika', 55332, 2116.27);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (114, 7, 'Grenadine', 64834, 279.6);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (115, 9, 'Calypso - Lemonade', 7163, 464.42);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (116, 8, 'Sauerkraut', 59275, 4353.86);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (117, 2, 'Cake Sheet Combo Party Pack', 64217, 3434.56);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (118, 4, 'Mushroom - Shitake, Fresh', 83115, 4949.75);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (119, 3, 'Gin - Gilbeys London, Dry', 74835, 1076.92);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (120, 7, 'Roe - White Fish', 25141, 9323.09);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (121, 10, 'Wiberg Super Cure', 41537, 7085.98);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (122, 2, 'Knife Plastic - White', 63110, 504.94);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (123, 2, 'Egg Patty Fried', 56716, 9093.57);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (124, 10, 'Cookies - Fortune', 2327, 3116.22);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (125, 4, 'Bar - Granola Trail Mix Fruit Nut', 70484, 5034.06);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (126, 9, 'Wine - Ruffino Chianti Classico', 68454, 7222.68);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (127, 2, 'Sardines', 88438, 3693.01);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (128, 10, 'Mussels - Frozen', 4784, 54.07);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (129, 8, 'Beef - Diced', 65705, 9199.83);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (130, 4, 'Wine - Clavet Saint Emilion', 33885, 466.91);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (131, 7, 'Pork - Bacon Cooked Slcd', 803, 9587.18);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (132, 1, 'Oil - Truffle, Black', 36900, 5437.67);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (133, 8, 'Soup - Cream Of Broccoli', 88225, 8531.99);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (134, 7, 'Oil - Sunflower', 50012, 3844.5);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (135, 5, 'Muffin Chocolate Individual Wrap', 33063, 6920.68);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (136, 1, 'Cookies - Oreo, 4 Pack', 71171, 3960.27);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (137, 3, 'Cod - Salted, Boneless', 63221, 1088.38);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (138, 1, 'Wine - Redchard Merritt', 54726, 8268.82);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (139, 3, 'Apple - Fuji', 77582, 4477.19);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (140, 7, 'Cookie Dough - Chunky', 72359, 9754.67);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (141, 3, 'Beef - Striploin', 41186, 4226.45);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (142, 4, 'Ice Cream - Vanilla', 29577, 6336.22);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (143, 1, 'Beef - Kindney, Whole', 99417, 3564.1);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (144, 3, 'Water - Spring Water 500ml', 20002, 5991.42);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (145, 4, 'Long Island Ice Tea', 15478, 9275.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (146, 3, 'Onions - Spanish', 42079, 1290.08);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (147, 6, 'Mushroom - Portebello', 3108, 165.25);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (148, 3, 'Pasta - Angel Hair', 45013, 4143.91);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (149, 8, 'Bacardi Mojito', 80736, 1468.38);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (150, 7, 'Dill Weed - Fresh', 89641, 2699.44);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (151, 10, 'Tilapia - Fillets', 24592, 6066.92);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (152, 6, 'Buffalo - Tenderloin', 80088, 2124.44);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (153, 10, 'Lid Tray - 12in Dome', 44920, 1285.01);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (154, 7, 'Pastry - Raisin Muffin - Mini', 48821, 175.12);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (155, 8, 'Pickle - Dill', 97358, 2223.28);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (156, 4, 'Cake - Miini Cheesecake Cherry', 55272, 9047.95);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (157, 6, 'Pastry - Chocolate Chip Muffin', 66715, 5337.13);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (158, 8, 'Kellogs Raisan Bran Bars', 27844, 5098.84);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (159, 5, 'Flour - Bran, Red', 35671, 7903.06);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (160, 2, 'Tomatoes', 66458, 7805.6);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (161, 4, 'Lamb - Loin, Trimmed, Boneless', 21346, 8314.63);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (162, 1, 'Sour Cream', 11409, 8140.79);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (163, 9, 'Turkey - Breast, Smoked', 23162, 2453.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (164, 2, 'Soup - Campbells', 69275, 4079.44);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (165, 2, 'Bread - Pita, Mini', 37221, 2626.1);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (166, 3, 'Eel - Smoked', 92192, 6512.35);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (167, 9, 'Creme De Menthe Green', 21220, 9488.65);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (168, 4, 'Milk - Chocolate 250 Ml', 54908, 6395.64);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (169, 3, 'Wine - White, Riesling, Henry Of', 2154, 245.07);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (170, 6, 'Steel Wool', 1902, 177.7);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (171, 9, 'Pepper - Chili Powder', 64161, 7911.5);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (172, 2, 'Appetizer - Sausage Rolls', 92149, 7918.09);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (173, 4, 'Star Anise, Whole', 95470, 6054.24);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (174, 4, 'Longos - Cheese Tortellini', 81859, 7330.92);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (175, 7, 'Pork - Inside', 71504, 8883.33);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (176, 4, 'Bread - Multigrain Oval', 95312, 4988.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (177, 10, 'Marzipan 50/50', 37714, 6788.78);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (178, 7, 'Pork - Sausage Casing', 55682, 3333.89);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (179, 9, 'Marzipan 50/50', 65933, 9872.27);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (180, 1, 'Dried Figs', 96675, 4413.66);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (181, 7, 'Blueberries', 98551, 7731.19);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (182, 4, 'Cheese - Cheddar, Old White', 54824, 3043.44);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (183, 5, 'Cheese Cloth', 96177, 57.46);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (184, 7, 'Sauce - Bernaise, Mix', 27479, 7292.14);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (185, 8, 'Beer - Blue', 93673, 6856.39);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (186, 3, 'Bar - Granola Trail Mix Fruit Nut', 69220, 7601.7);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (187, 10, 'Chestnuts - Whole,canned', 28220, 7907.38);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (188, 8, 'Wine - White, Riesling, Henry Of', 81465, 6631.99);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (189, 8, 'Quinoa', 34109, 1721.34);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (190, 8, 'Lamb Shoulder Boneless Nz', 68363, 4814.79);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (191, 2, 'Wine - Shiraz Wolf Blass Premium', 6628, 1637.81);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (192, 4, 'Apples - Sliced / Wedge', 93678, 6026.81);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (193, 10, 'Chips - Assorted', 61027, 1885.67);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (194, 10, 'Rum - Cream, Amarula', 70322, 6977.9);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (195, 9, 'Cotton Wet Mop 16 Oz', 71894, 9627.87);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (196, 8, 'Lid Tray - 16in Dome', 33920, 2486.31);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (197, 10, 'Oil - Cooking Spray', 76617, 5187.02);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (198, 7, 'Wine - Sherry Dry Sack, William', 89973, 597.26);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (199, 3, 'Sachet', 87607, 3907.59);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (200, 2, 'Wine - White, Riesling, Henry Of', 70745, 2328.51);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (201, 1, 'Lettuce - Green Leaf', 79810, 99.2);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (202, 4, 'Tomatoes', 75761, 5523.63);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (203, 1, 'Wine - Casillero Del Diablo', 3270, 3882.69);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (204, 7, 'Olives - Nicoise', 76122, 7129.07);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (205, 1, 'Cumin - Whole', 10160, 7389.44);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (206, 8, 'Venison - Denver Leg Boneless', 22733, 193.52);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (207, 9, 'Oven Mitts - 15 Inch', 45917, 5440.61);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (208, 1, 'Chicken - Leg / Back Attach', 21954, 6307.22);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (209, 7, 'Parsley Italian - Fresh', 59346, 537.05);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (210, 5, 'Bread - Pita, Mini', 92100, 8025.44);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (211, 2, 'Butter - Salted, Micro', 79090, 474.04);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (212, 2, 'Rhubarb', 32789, 6402.48);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (213, 5, 'Bacon Strip Precooked', 3081, 8647.82);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (214, 1, 'Kiwi', 34558, 3468.93);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (215, 5, 'Wine - Barolo Fontanafredda', 88201, 1044.25);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (216, 6, 'Rice - Wild', 1495, 4549.47);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (217, 6, 'Bread Base - Toscano', 57478, 5094.26);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (218, 5, 'Beef - Tender Tips', 62690, 3654.55);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (219, 8, 'Sole - Iqf', 71162, 3946.53);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (220, 1, 'Ecolab - Balanced Fusion', 2507, 6452.62);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (221, 9, 'Chestnuts - Whole,canned', 14166, 2926.85);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (222, 2, 'Juice - Mango', 59001, 5424.0);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (223, 2, 'Soup Campbells Turkey Veg.', 19146, 376.53);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (224, 2, 'Filling - Mince Meat', 21637, 9139.08);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (225, 3, 'Browning Caramel Glace', 25943, 1858.68);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (226, 8, 'Ecolab Crystal Fusion', 60518, 2484.46);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (227, 1, 'Pastry - Chocolate Marble Tea', 16988, 834.41);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (228, 6, 'Papadam', 98402, 1725.56);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (229, 9, 'Glucose', 63304, 3558.26);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (230, 1, 'Muffin Batt - Carrot Spice', 3483, 1249.07);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (231, 6, 'Wine - Cabernet Sauvignon', 40396, 918.38);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (232, 6, 'Pepper - Green, Chili', 40588, 3871.68);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (233, 6, 'Syrup - Monin - Blue Curacao', 98006, 4392.63);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (234, 4, 'Juice - Apple, 500 Ml', 6218, 3391.81);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (235, 7, 'Sausage - Liver', 21306, 8056.27);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (236, 10, 'Peppercorns - Green', 86542, 6564.27);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (237, 8, 'Pectin', 92679, 2925.4);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (238, 10, 'Spring Roll Wrappers', 57490, 4593.56);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (239, 6, 'Coffee - Decaffeinato Coffee', 49169, 1034.62);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (240, 5, 'Jerusalem Artichoke', 31946, 7526.23);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (241, 6, 'Bagel - Plain', 2875, 8397.01);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (242, 9, 'Truffle Cups Green', 89867, 9239.1);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (243, 2, 'Flower - Commercial Spider', 10791, 3397.2);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (244, 9, 'Longos - Assorted Sandwich', 60036, 6584.02);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (245, 10, 'Soup - Cream Of Broccoli, Dry', 43381, 1042.4);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (246, 10, 'Lid Tray - 12in Dome', 92093, 263.19);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (247, 1, 'Juice - Grape, White', 42015, 9522.1);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (248, 10, 'Lamb - Shoulder, Boneless', 19539, 5954.53);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (249, 9, 'Godiva White Chocolate', 68585, 6926.62);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (250, 2, 'Flour - Strong Pizza', 84455, 9100.29);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (251, 8, 'Broom - Corn', 96409, 4027.96);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (252, 8, 'Beef - Bones, Marrow', 4623, 3304.35);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (253, 5, 'Muskox - French Rack', 47225, 7472.6);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (254, 3, 'Cookie - Oatmeal', 40249, 4758.16);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (255, 1, 'Cheese - Grie Des Champ', 35059, 2289.7);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (256, 2, 'Lobster - Tail 6 Oz', 90070, 3191.98);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (257, 8, 'Cape Capensis - Fillet', 24748, 7466.73);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (258, 1, 'Ginger - Fresh', 8587, 6690.99);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (259, 10, 'Tea - Herbal I Love Lemon', 54516, 4907.16);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (260, 2, 'Melon - Cantaloupe', 73651, 9174.1);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (261, 7, 'Mushroom - Oyster, Fresh', 69879, 7475.61);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (262, 7, 'Wine - Bourgogne 2002, La', 70, 2376.4);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (263, 3, 'Chocolate - Semi Sweet', 49369, 2655.91);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (264, 5, 'Beans - Green', 72113, 3952.62);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (265, 10, 'Pork - Backs - Boneless', 94656, 1494.39);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (266, 5, 'Puree - Guava', 87543, 4350.4);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (267, 8, 'Taro Root', 46851, 7978.55);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (268, 7, 'Wine - Bouchard La Vignee Pinot', 12321, 637.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (269, 10, 'Bread - Flat Bread', 78261, 6159.44);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (270, 8, 'Blouse / Shirt / Sweater', 11171, 6742.16);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (271, 4, 'Pie Filling - Apple', 18988, 324.14);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (272, 3, 'Wine - Hardys Bankside Shiraz', 8783, 622.81);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (273, 6, 'Eel - Smoked', 41421, 9404.41);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (274, 3, 'Wine - White, Gewurtzraminer', 92333, 1984.26);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (275, 9, 'Bread - Granary Small Pull', 62732, 74.78);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (276, 10, 'Banana - Green', 17797, 3603.81);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (277, 3, 'Smoked Tongue', 57248, 748.04);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (278, 2, 'Figs', 20995, 4411.15);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (279, 3, 'Squash - Guords', 3785, 3771.23);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (280, 4, 'Split Peas - Yellow, Dry', 79402, 5293.66);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (281, 4, 'Puff Pastry - Sheets', 6794, 6084.45);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (282, 2, 'Lychee', 79756, 8941.17);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (283, 6, 'Oxtail - Cut', 21063, 5669.19);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (284, 9, 'Chocolate - Semi Sweet', 21215, 2382.52);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (285, 8, 'Juice - Orange, 341 Ml', 27109, 801.62);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (286, 3, 'Shrimp - 31/40', 45598, 1978.4);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (287, 7, 'Sobe - Berry Energy', 88713, 5889.21);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (288, 8, 'Beans - Kidney White', 86145, 8403.9);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (289, 1, 'Pineapple - Regular', 51828, 2975.06);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (290, 2, 'Salmon - Atlantic, Skin On', 32133, 4726.95);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (291, 2, 'Island Oasis - Wildberry', 23432, 1761.35);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (292, 10, 'Orange Roughy 4/6 Oz', 28948, 276.61);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (293, 2, 'Rosemary - Primerba, Paste', 34874, 2491.63);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (294, 9, 'Pork - Backfat', 67325, 4451.84);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (295, 7, 'Chicken - Wieners', 92620, 7797.35);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (296, 4, 'White Fish - Filets', 52848, 9675.53);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (297, 3, 'French Pastry - Mini Chocolate', 56575, 874.26);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (298, 3, 'Cheese - Pont Couvert', 91761, 6584.82);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (299, 3, 'Cream - 35%', 19752, 4458.26);
insert into products (product_id, category_id, product_name, product_quantity, unit_price) values (300, 8, 'Oil - Shortening,liqud, Fry', 11334, 8506.44);

