insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (1, 645, 'Mercury', 'Eurovan', 1954, 948);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (2, 837, 'Land Rover', 'Lancer', 1911, 781);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (3, 292, 'Mitsubishi', 'Intrepid', 1921, 744);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (4, 326, 'Acura', 'Lancer', 2017, 108);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (5, 883, 'Acura', 'Civic', 2014, 131);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (6, 256, 'GMC', 'Golf', 1981, 540);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (7, 819, 'Chevrolet', 'Lancer', 1933, 596);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (8, 553, 'Dodge', 'Golf', 1950, 461);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (9, 220, 'Dodge', 'ZDX', 1993, 772);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (10, 439, 'Dodge', 'Eurovan', 1999, 447);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (11, 453, 'Mercury', 'Tracer', 1946, 23);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (12, 641, 'Honda', 'Dakota', 1989, 459);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (13, 900, 'Land Rover', 'Eclipse', 2014, 239);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (14, 670, 'Mercury', 'Golf', 1943, 581);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (15, 690, 'Volkswagen', 'Dakota', 1985, 938);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (16, 308, 'Mercury', 'Express 2500', 1947, 415);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (17, 716, 'Land Rover', 'Express 2500', 2008, 151);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (18, 531, 'Land Rover', 'Lancer', 2003, 125);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (19, 244, 'GMC', 'Tracer', 1949, 764);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (20, 999, 'Acura', 'Range Rover', 1923, 660);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (21, 348, 'Acura', 'Intrepid', 2007, 606);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (22, 152, 'Land Rover', 'Golf', 1976, 163);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (23, 456, 'Mazda', 'Dakota', 1992, 104);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (24, 734, 'Mercury', 'ZDX', 1947, 238);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (25, 244, 'Mitsubishi', 'ZDX', 1941, 292);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (26, 61, 'Honda', 'Express 2500', 1995, 789);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (27, 324, 'Mitsubishi', 'Yukon XL 1500', 1972, 629);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (28, 907, 'Land Rover', 'Dakota', 1955, 608);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (29, 929, 'Volkswagen', 'Tracer', 1957, 129);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (30, 310, 'Dodge', 'CX-7', 1936, 246);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (31, 895, 'Acura', 'Dakota', 2004, 755);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (32, 960, 'Chevrolet', 'Golf', 1926, 744);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (33, 702, 'Honda', 'Intrepid', 1986, 123);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (34, 284, 'Chevrolet', 'Civic', 1937, 134);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (35, 181, 'Mazda', 'CX-7', 1931, 424);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (36, 969, 'Volkswagen', 'CX-7', 1926, 372);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (37, 728, 'GMC', 'Yukon XL 1500', 1979, 376);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (38, 703, 'Honda', 'Dakota', 1947, 230);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (39, 825, 'GMC', 'Range Rover', 2009, 116);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (40, 455, 'Honda', 'CX-7', 1970, 936);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (41, 912, 'Mitsubishi', 'ZDX', 2007, 89);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (42, 985, 'Mercury', 'CX-7', 1947, 79);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (43, 48, 'Volkswagen', 'Tracer', 2002, 155);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (44, 161, 'Mazda', 'Eclipse', 1956, 564);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (45, 876, 'Mercury', 'Eclipse', 1966, 385);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (46, 296, 'Honda', 'Express 2500', 2007, 299);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (47, 121, 'Land Rover', 'Yukon XL 1500', 1950, 574);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (48, 749, 'Dodge', 'Range Rover', 1916, 749);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (49, 332, 'Mitsubishi', 'Lancer', 1949, 227);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (50, 840, 'Honda', 'Eurovan', 2015, 45);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (51, 780, 'Mitsubishi', 'CX-7', 1940, 199);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (52, 174, 'Honda', 'CX-7', 1959, 989);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (53, 78, 'Mazda', 'Express 2500', 1940, 299);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (54, 726, 'Mitsubishi', 'Intrepid', 1937, 250);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (55, 275, 'Mazda', 'CX-7', 2012, 298);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (56, 112, 'Land Rover', 'Yukon XL 1500', 1973, 724);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (57, 186, 'Mercury', 'Eurovan', 1914, 371);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (58, 41, 'Chevrolet', 'Lancer', 1984, 811);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (59, 185, 'Land Rover', 'Eclipse', 2008, 640);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (60, 127, 'Land Rover', 'Intrepid', 1994, 706);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (61, 927, 'Volkswagen', 'ZDX', 1955, 151);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (62, 52, 'Mitsubishi', 'Civic', 2004, 677);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (63, 58, 'Mercury', 'Range Rover', 2014, 647);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (64, 313, 'Dodge', 'Range Rover', 1933, 597);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (65, 459, 'Chevrolet', 'Civic', 2007, 369);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (66, 627, 'Volkswagen', 'Eurovan', 1990, 849);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (67, 103, 'Mercury', 'Eurovan', 1991, 489);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (68, 706, 'Mitsubishi', 'Yukon XL 1500', 1940, 770);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (69, 3, 'Mitsubishi', 'Lancer', 1989, 522);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (70, 938, 'Land Rover', 'CX-7', 1915, 56);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (71, 989, 'Mazda', 'Golf', 1974, 992);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (72, 524, 'Acura', 'Golf', 1975, 150);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (73, 913, 'Land Rover', 'ZDX', 1962, 511);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (74, 792, 'Acura', 'Eclipse', 1969, 632);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (75, 364, 'Mercury', 'Express 2500', 1918, 1);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (76, 293, 'Mazda', 'Lancer', 1997, 587);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (77, 873, 'Mercury', 'ZDX', 1919, 845);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (78, 963, 'Land Rover', 'Eurovan', 1952, 728);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (79, 814, 'Mitsubishi', 'Eclipse', 2014, 806);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (80, 532, 'Honda', 'Lancer', 1979, 538);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (81, 868, 'Volkswagen', 'Golf', 2017, 495);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (82, 399, 'Mitsubishi', 'Tracer', 1989, 778);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (83, 832, 'Land Rover', 'Yukon XL 1500', 1972, 253);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (84, 871, 'Volkswagen', 'Range Rover', 1912, 755);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (85, 480, 'Dodge', 'Range Rover', 2008, 443);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (86, 23, 'Acura', 'Yukon XL 1500', 1999, 193);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (87, 585, 'Mazda', 'ZDX', 2012, 21);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (88, 725, 'Mazda', 'CX-7', 1979, 273);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (89, 84, 'Acura', 'Eclipse', 1917, 912);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (90, 710, 'Acura', 'Range Rover', 1911, 511);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (91, 746, 'Mitsubishi', 'Civic', 1994, 986);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (92, 840, 'Dodge', 'Lancer', 1993, 38);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (93, 800, 'Mitsubishi', 'Golf', 1945, 171);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (94, 42, 'Mercury', 'CX-7', 1947, 713);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (95, 42, 'Dodge', 'Range Rover', 1949, 127);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (96, 56, 'Mitsubishi', 'Tracer', 1940, 200);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (97, 364, 'Dodge', 'Civic', 2001, 888);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (98, 640, 'GMC', 'Eurovan', 1933, 969);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (99, 725, 'GMC', 'Range Rover', 2013, 186);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (100, 52, 'Acura', 'Eurovan', 1960, 119);
insert into vehicles (vehicle_id, license_plate, make, model, year, driver_id) values (101, 564, 'Acura', 'Eclipse', 1968, 268);
